services:
  lcv.exception_listener:
    class: LCV\ExceptionPackBundle\EventListener\ExceptionListener
    arguments: ["@security.token_storage", "@swiftmailer.mailer.abstract", "@translator",
                "", "", ""]

    tags:
      - { name: kernel.event_listener, event: kernel.exception, priority: 1 }
