services:
  lcv.exception_listener:
    class: LCV\ExceptionPackBundle\EventListener\ExceptionListener
    arguments: [null, null, null,
                "", "", ""]
    tags:
      - { name: kernel.event_listener, event: kernel.exception, priority: 1 }
